# Generated by Django 3.2.23 on 2024-01-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '相談',
            },
        ),
        migrations.CreateModel(
            name='CustomerVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10, verbose_name='性別')),
                ('age', models.CharField(max_length=5, verbose_name='年齢')),
                ('job', models.CharField(max_length=20, verbose_name='職業')),
                ('description', models.CharField(max_length=255, verbose_name='内容')),
            ],
            options={
                'verbose_name': '利用者の声',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('company_name', models.CharField(max_length=255, verbose_name='会社名')),
                ('business_content', models.CharField(max_length=255, verbose_name='業務内容')),
                ('position', models.CharField(max_length=255, verbose_name='募集ポジション')),
                ('location', models.CharField(max_length=255, verbose_name='勤務地')),
                ('applicant_age', models.CharField(max_length=255, verbose_name='応募想定年齢')),
                ('annual_fee', models.CharField(max_length=255, verbose_name='理論年収')),
                ('picture', models.ImageField(default='', max_length=255, upload_to='./media/', verbose_name='添付画像')),
            ],
            options={
                'verbose_name': '求人例',
            },
        ),
    ]
